//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ButtonsIcon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ButtonsIcon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ButtonsIcon", typeof(ButtonsIcon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-account-check.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-check-circle.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-archive-plus.
        /// </summary>
        public static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-calculator-variant.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-close-circle.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-cancel.
        /// </summary>
        public static string CancelTsp {
            get {
                return ResourceManager.GetString("CancelTsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-shield-key.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-checkbox-multiple-marked-outline.
        /// </summary>
        public static string CheckAll {
            get {
                return ResourceManager.GetString("CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-backspace.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-check.
        /// </summary>
        public static string Confirm1 {
            get {
                return ResourceManager.GetString("Confirm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-check-all.
        /// </summary>
        public static string Confirm2 {
            get {
                return ResourceManager.GetString("Confirm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-content-copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-plus.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-trash-can.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-dots-horizontal.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-account-details-outline.
        /// </summary>
        public static string DiscoveryAccountFlow {
            get {
                return ResourceManager.GetString("DiscoveryAccountFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-account-multiple-outline.
        /// </summary>
        public static string DiscoveryAccountHolderInfo {
            get {
                return ResourceManager.GetString("DiscoveryAccountHolderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-credit-card-check-outline.
        /// </summary>
        public static string DiscoveryAccountInfo {
            get {
                return ResourceManager.GetString("DiscoveryAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-account.
        /// </summary>
        public static string DiscoveryCustomerInfo {
            get {
                return ResourceManager.GetString("DiscoveryCustomerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-account-star-outline.
        /// </summary>
        public static string DiscoveryExtra {
            get {
                return ResourceManager.GetString("DiscoveryExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-star-check-outline.
        /// </summary>
        public static string DiscoveryMark {
            get {
                return ResourceManager.GetString("DiscoveryMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-comment-account-outline.
        /// </summary>
        public static string DiscoveryOpinion {
            get {
                return ResourceManager.GetString("DiscoveryOpinion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-text-box-check-outline.
        /// </summary>
        public static string DiscoveryUserActionType {
            get {
                return ResourceManager.GetString("DiscoveryUserActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-pencil.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-file-edit.
        /// </summary>
        public static string EditTsp {
            get {
                return ResourceManager.GetString("EditTsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-close-circle-outline.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-microsoft-excel.
        /// </summary>
        public static string ExportExcel {
            get {
                return ResourceManager.GetString("ExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-file-document-remove.
        /// </summary>
        public static string FileDelete {
            get {
                return ResourceManager.GetString("FileDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-file-download.
        /// </summary>
        public static string FileDownload {
            get {
                return ResourceManager.GetString("FileDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-cloud-upload.
        /// </summary>
        public static string FileUpload {
            get {
                return ResourceManager.GetString("FileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-cloud-upload.
        /// </summary>
        public static string FileUploadOpen {
            get {
                return ResourceManager.GetString("FileUploadOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-filter-cog.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-bank-transfer-in.
        /// </summary>
        public static string FraudBranchResponse {
            get {
                return ResourceManager.GetString("FraudBranchResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-cloud-download.
        /// </summary>
        public static string FraudEvidenceReceive {
            get {
                return ResourceManager.GetString("FraudEvidenceReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-cloud-upload.
        /// </summary>
        public static string FraudEvidenceSend {
            get {
                return ResourceManager.GetString("FraudEvidenceSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-account-check-outline.
        /// </summary>
        public static string FraudFinalization {
            get {
                return ResourceManager.GetString("FraudFinalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-account-lock-outline.
        /// </summary>
        public static string FraudManualBlock {
            get {
                return ResourceManager.GetString("FraudManualBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-account-lock-open-outline.
        /// </summary>
        public static string FraudManualBlockCancel {
            get {
                return ResourceManager.GetString("FraudManualBlockCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-account-cancel-outline.
        /// </summary>
        public static string FraudManualLimit {
            get {
                return ResourceManager.GetString("FraudManualLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-account-off-outline.
        /// </summary>
        public static string FraudManualLimitCancel {
            get {
                return ResourceManager.GetString("FraudManualLimitCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-comment-account-outline.
        /// </summary>
        public static string FraudOpinion {
            get {
                return ResourceManager.GetString("FraudOpinion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-bank-transfer-out.
        /// </summary>
        public static string FraudSendToBranch {
            get {
                return ResourceManager.GetString("FraudSendToBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-account-lock-outline.
        /// </summary>
        public static string FraudSystemBlock {
            get {
                return ResourceManager.GetString("FraudSystemBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-account-lock-open-outline.
        /// </summary>
        public static string FraudSystemBlockCancel {
            get {
                return ResourceManager.GetString("FraudSystemBlockCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-account-cancel-outline.
        /// </summary>
        public static string FraudSystemLimit {
            get {
                return ResourceManager.GetString("FraudSystemLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-account-off-outline.
        /// </summary>
        public static string FraudSystemLimitCancel {
            get {
                return ResourceManager.GetString("FraudSystemLimitCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-history.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-history.
        /// </summary>
        public static string HistoryAction {
            get {
                return ResourceManager.GetString("HistoryAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-chevron-right.
        /// </summary>
        public static string IconBefore {
            get {
                return ResourceManager.GetString("IconBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-page-last.
        /// </summary>
        public static string IconFirst {
            get {
                return ResourceManager.GetString("IconFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-page-first.
        /// </summary>
        public static string IconLast {
            get {
                return ResourceManager.GetString("IconLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-chevron-left.
        /// </summary>
        public static string IconNext {
            get {
                return ResourceManager.GetString("IconNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-account-remove.
        /// </summary>
        public static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-information-variant-circle-outline.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-login-variant.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-power-standby.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-hand-back-left-outline.
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-menu-up.
        /// </summary>
        public static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-dots-horizontal.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-close-thick.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-view-grid-plus.
        /// </summary>
        public static string PageSizeChange {
            get {
                return ResourceManager.GetString("PageSizeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-content-save-plus.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-close-box-outline.
        /// </summary>
        public static string Reject1 {
            get {
                return ResourceManager.GetString("Reject1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-close-box-multiple.
        /// </summary>
        public static string Reject2 {
            get {
                return ResourceManager.GetString("Reject2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-playlist-remove.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-arrow-right-bold.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-content-save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-magnify.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-gesture-tap.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-cog.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-magnify.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-eye-outline.
        /// </summary>
        public static string ShowDetail {
            get {
                return ResourceManager.GetString("ShowDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-check-circle-outline.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-checkbox-multiple-blank-outline.
        /// </summary>
        public static string UnCheckAll {
            get {
                return ResourceManager.GetString("UnCheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-check-underline.
        /// </summary>
        public static string Understood {
            get {
                return ResourceManager.GetString("Understood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-pencil.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-clock-edit-outline.
        /// </summary>
        public static string VersionChanges {
            get {
                return ResourceManager.GetString("VersionChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-monitor-eye.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-alert-outline.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi mdi-check-bold.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
