//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Buttons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Buttons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Buttons", typeof(Buttons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعمال.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آرشیو.
        /// </summary>
        public static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محاسبه.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابطال.
        /// </summary>
        public static string CancelTsp {
            get {
                return ResourceManager.GetString("CancelTsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر رمز عبور.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب نمودن همه.
        /// </summary>
        public static string CheckAll {
            get {
                return ResourceManager.GetString("CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاک کردن.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بستن.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تائید اول.
        /// </summary>
        public static string Confirm1 {
            get {
                return ResourceManager.GetString("Confirm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تائید دوم.
        /// </summary>
        public static string Confirm2 {
            get {
                return ResourceManager.GetString("Confirm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کپی.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزئیات.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گردش حساب.
        /// </summary>
        public static string DiscoveryAccountFlow {
            get {
                return ResourceManager.GetString("DiscoveryAccountFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صاحبان حساب.
        /// </summary>
        public static string DiscoveryAccountHolderInfo {
            get {
                return ResourceManager.GetString("DiscoveryAccountHolderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حساب.
        /// </summary>
        public static string DiscoveryAccountInfo {
            get {
                return ResourceManager.GetString("DiscoveryAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتری.
        /// </summary>
        public static string DiscoveryCustomerInfo {
            get {
                return ResourceManager.GetString("DiscoveryCustomerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات خاص حساب.
        /// </summary>
        public static string DiscoveryExtra {
            get {
                return ResourceManager.GetString("DiscoveryExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to علامت گذاری.
        /// </summary>
        public static string DiscoveryMark {
            get {
                return ResourceManager.GetString("DiscoveryMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نظر.
        /// </summary>
        public static string DiscoveryOpinion {
            get {
                return ResourceManager.GetString("DiscoveryOpinion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع عملیات.
        /// </summary>
        public static string DiscoveryUserActionType {
            get {
                return ResourceManager.GetString("DiscoveryUserActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اصلاح.
        /// </summary>
        public static string EditTsp {
            get {
                return ResourceManager.GetString("EditTsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروجی به اکسل.
        /// </summary>
        public static string ExportExcel {
            get {
                return ResourceManager.GetString("ExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف فایل.
        /// </summary>
        public static string FileDelete {
            get {
                return ResourceManager.GetString("FileDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت فایل.
        /// </summary>
        public static string FileDownload {
            get {
                return ResourceManager.GetString("FileDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگذاری فایل.
        /// </summary>
        public static string FileUpload {
            get {
                return ResourceManager.GetString("FileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگذاری.
        /// </summary>
        public static string FileUploadOpen {
            get {
                return ResourceManager.GetString("FileUploadOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلتر.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاسخ شعبه.
        /// </summary>
        public static string FraudBranchResponse {
            get {
                return ResourceManager.GetString("FraudBranchResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت مدارک تقلب.
        /// </summary>
        public static string FraudEvidenceReceive {
            get {
                return ResourceManager.GetString("FraudEvidenceReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال مدارک تقلب.
        /// </summary>
        public static string FraudEvidenceSend {
            get {
                return ResourceManager.GetString("FraudEvidenceSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نهایی تقلب.
        /// </summary>
        public static string FraudFinalization {
            get {
                return ResourceManager.GetString("FraudFinalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسدودسازی دستی.
        /// </summary>
        public static string FraudManualBlock {
            get {
                return ResourceManager.GetString("FraudManualBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو مسدودسازی دستی.
        /// </summary>
        public static string FraudManualBlockCancel {
            get {
                return ResourceManager.GetString("FraudManualBlockCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محدودسازی دستی.
        /// </summary>
        public static string FraudManualLimit {
            get {
                return ResourceManager.GetString("FraudManualLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو محدودسازی دستی.
        /// </summary>
        public static string FraudManualLimitCancel {
            get {
                return ResourceManager.GetString("FraudManualLimitCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نظر.
        /// </summary>
        public static string FraudOpinion {
            get {
                return ResourceManager.GetString("FraudOpinion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت مدارک تقلب.
        /// </summary>
        public static string FraudReceiveDocuments {
            get {
                return ResourceManager.GetString("FraudReceiveDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال به شعبه.
        /// </summary>
        public static string FraudSendToBranch {
            get {
                return ResourceManager.GetString("FraudSendToBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسدودسازی سیستمی.
        /// </summary>
        public static string FraudSystemBlock {
            get {
                return ResourceManager.GetString("FraudSystemBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو مسدودسازی سیستمی.
        /// </summary>
        public static string FraudSystemBlockCancel {
            get {
                return ResourceManager.GetString("FraudSystemBlockCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محدودسازی سیستمی.
        /// </summary>
        public static string FraudSystemLimit {
            get {
                return ResourceManager.GetString("FraudSystemLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو محدودسازی سیستمی.
        /// </summary>
        public static string FraudSystemLimitCancel {
            get {
                return ResourceManager.GetString("FraudSystemLimitCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخچه.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخچه عملیات.
        /// </summary>
        public static string HistoryAction {
            get {
                return ResourceManager.GetString("HistoryAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IconBefore.
        /// </summary>
        public static string IconBefore {
            get {
                return ResourceManager.GetString("IconBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IconFirst.
        /// </summary>
        public static string IconFirst {
            get {
                return ResourceManager.GetString("IconFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IconLast.
        /// </summary>
        public static string IconLast {
            get {
                return ResourceManager.GetString("IconLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IconNext.
        /// </summary>
        public static string IconNext {
            get {
                return ResourceManager.GetString("IconNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیر فعال.
        /// </summary>
        public static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیشتر.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیر.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باز شدن / بسته شدن.
        /// </summary>
        public static string OpenClose {
            get {
                return ResourceManager.GetString("OpenClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر اندازه صفحه.
        /// </summary>
        public static string PageSizeChange {
            get {
                return ResourceManager.GetString("PageSizeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رد اول.
        /// </summary>
        public static string Reject1 {
            get {
                return ResourceManager.GetString("Reject1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رد دوم.
        /// </summary>
        public static string Reject2 {
            get {
                return ResourceManager.GetString("Reject2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالت اولیه.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش جزئیات.
        /// </summary>
        public static string ShowDetail {
            get {
                return ResourceManager.GetString("ShowDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موفق.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از انتخاب خارج نمودن همه.
        /// </summary>
        public static string UnCheckAll {
            get {
                return ResourceManager.GetString("UnCheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متوجه شدم.
        /// </summary>
        public static string Understood {
            get {
                return ResourceManager.GetString("Understood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بروزرسانی.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییرات نسخه.
        /// </summary>
        public static string VersionChanges {
            get {
                return ResourceManager.GetString("VersionChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هشدار.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بلی.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
