//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DefaultValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DefaultValues", typeof(DefaultValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سامانه مودیان مالیاتی.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        public static string ApplicationVersion {
            get {
                return ResourceManager.GetString("ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to position-absolute top-0 start-100 translate-middle badge rounded-pill bg-white.
        /// </summary>
        public static string ButtonBadge {
            get {
                return ResourceManager.GetString("ButtonBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://nazmaran.com.
        /// </summary>
        public static string CompanyLink {
            get {
                return ResourceManager.GetString("CompanyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nazmaran.com.
        /// </summary>
        public static string CompanyLinkTitle {
            get {
                return ResourceManager.GetString("CompanyLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content/images/Logo/LogoCompany.png.
        /// </summary>
        public static string CompanyLogo {
            get {
                return ResourceManager.GetString("CompanyLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت توسعه راهکار نظم آران.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi-14px.
        /// </summary>
        public static string IconSize14 {
            get {
                return ResourceManager.GetString("IconSize14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi-18px.
        /// </summary>
        public static string IconSize18 {
            get {
                return ResourceManager.GetString("IconSize18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi-24px.
        /// </summary>
        public static string IconSize24 {
            get {
                return ResourceManager.GetString("IconSize24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi-36px.
        /// </summary>
        public static string IconSize36 {
            get {
                return ResourceManager.GetString("IconSize36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi-48px.
        /// </summary>
        public static string IconSize48 {
            get {
                return ResourceManager.GetString("IconSize48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdi-64px.
        /// </summary>
        public static string IconSize64 {
            get {
                return ResourceManager.GetString("IconSize64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string MenuIdActivityReport {
            get {
                return ResourceManager.GetString("MenuIdActivityReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string MenuIdIndex {
            get {
                return ResourceManager.GetString("MenuIdIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string MenuIdProfile {
            get {
                return ResourceManager.GetString("MenuIdProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        public static string MoadianNumberOfValidDate {
            get {
                return ResourceManager.GetString("MoadianNumberOfValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content/images/Logo/Logo.png.
        /// </summary>
        public static string OrganizationLogo {
            get {
                return ResourceManager.GetString("OrganizationLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content/images/Logo/LogoMini.png.
        /// </summary>
        public static string OrganizationLogoMini {
            get {
                return ResourceManager.GetString("OrganizationLogoMini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت بیمه ایران.
        /// </summary>
        public static string OrganizationName {
            get {
                return ResourceManager.GetString("OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string PageNumber {
            get {
                return ResourceManager.GetString("PageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
    }
}
