//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MenuDetails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuDetails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MenuDetails", typeof(MenuDetails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر رمز عبور.
        /// </summary>
        public static string ChangePasswordByAdmin {
            get {
                return ResourceManager.GetString("ChangePasswordByAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گردش حساب مرتبط.
        /// </summary>
        public static string DiscoveryAccountFlows {
            get {
                return ResourceManager.GetString("DiscoveryAccountFlows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موارد کشف شده صاحبان حساب.
        /// </summary>
        public static string DiscoveryAccountHolders {
            get {
                return ResourceManager.GetString("DiscoveryAccountHolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موارد کشف شده شماره حساب.
        /// </summary>
        public static string DiscoveryAccounts {
            get {
                return ResourceManager.GetString("DiscoveryAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات خاص حساب.
        /// </summary>
        public static string DiscoveryExtras {
            get {
                return ResourceManager.GetString("DiscoveryExtras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to علامت گذاری کشف مورد.
        /// </summary>
        public static string DiscoveryMarks {
            get {
                return ResourceManager.GetString("DiscoveryMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نظر کشف مورد.
        /// </summary>
        public static string DiscoveryOpinions {
            get {
                return ResourceManager.GetString("DiscoveryOpinions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخچه عملیات.
        /// </summary>
        public static string DiscoveryUserActionTypes {
            get {
                return ResourceManager.GetString("DiscoveryUserActionTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدارک تقلب.
        /// </summary>
        public static string FraudEvidences {
            get {
                return ResourceManager.GetString("FraudEvidences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نظر تقلب.
        /// </summary>
        public static string FraudOpinions {
            get {
                return ResourceManager.GetString("FraudOpinions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخچه عملیات.
        /// </summary>
        public static string UserFraudActions {
            get {
                return ResourceManager.GetString("UserFraudActions", resourceCulture);
            }
        }
    }
}
