//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ رکوردی برای محاسبه وجود ندارد.
        /// </summary>
        public static string CalcRecordEmptyText {
            get {
                return ResourceManager.GetString("CalcRecordEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توجه : در صورتی که این رکورد باطل نشده است، ابتدا آن را باطل نموده، سپس اصلاح نمایید..
        /// </summary>
        public static string CancelBeforeFix {
            get {
                return ResourceManager.GetString("CancelBeforeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا از ابطال صورتحساب کاملا اطمینان حاصل فرمایید، با انجام عملیات ابطال، صورتحساب باطل شده،  دیگر با کد و تاریخ فعلی قابل صدور نمیباشد و صورتحساب میبایست با کد و تاریخ جدید ثبت شود..
        /// </summary>
        public static string CancleTspMessage {
            get {
                return ResourceManager.GetString("CancleTspMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با ویرایش رکورد خطادار صورتحساب مجددا ارسال می گردد، در صورتی که بازه تاریخ مجاز آن به پایان رسیده باشد،  با تاریخ به روز ارسال می گردد، آیا همچنان مایل به ویرایش رکورد هستید؟.
        /// </summary>
        public static string EditFailedMessage {
            get {
                return ResourceManager.GetString("EditFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ موردی برای نمایش وجود ندارد.
        /// </summary>
        public static string GridEmptyText {
            get {
                return ResourceManager.GetString("GridEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خواهشا از منحصر به فرد بودن شماره صورتحساب اطمینان حاصل فرمایید..
        /// </summary>
        public static string InnoUniqueMessage {
            get {
                return ResourceManager.GetString("InnoUniqueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مورد انتخاب شده است.
        /// </summary>
        public static string ItemsSelected {
            get {
                return ResourceManager.GetString("ItemsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال انجام عملیات {0}، لطفا منتظر بمانید.
        /// </summary>
        public static string LoadingButtonWatingText {
            get {
                return ResourceManager.GetString("LoadingButtonWatingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال پردازش، لطفا کمی صبر کنید.
        /// </summary>
        public static string LoadingProgressText {
            get {
                return ResourceManager.GetString("LoadingProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال بارگذاری اطلاعات، لطفا کمی صبر کنید.
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات روی رکوردها.
        /// </summary>
        public static string OperationsOnRecords {
            get {
                return ResourceManager.GetString("OperationsOnRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه {0} از {1} ({2} رکورد).
        /// </summary>
        public static string PagingSummaryFormat {
            get {
                return ResourceManager.GetString("PagingSummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با عرض پوزش، چیزی در این آدرس وجود ندارد.
        /// </summary>
        public static string RouterNotFound {
            get {
                return ResourceManager.GetString("RouterNotFound", resourceCulture);
            }
        }
    }
}
