//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما غیرفعال شده است!.
        /// </summary>
        public static string AccountInActive {
            get {
                return ResourceManager.GetString("AccountInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرویس تیس در دسترس نیست یا خروجی سرویس خالی است.
        /// </summary>
        public static string CalcTissError {
            get {
                return ResourceManager.GetString("CalcTissError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به علت نامناسب بودن اطلاعات ورودی عملیات با موفقیت انجام نشد..
        /// </summary>
        public static string CancelFailedMessage {
            get {
                return ResourceManager.GetString("CancelFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف این {0} وجود ندارد!.
        /// </summary>
        public static string CanNotDelete {
            get {
                return ResourceManager.GetString("CanNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن همراه قبلا تایید شده است!.
        /// </summary>
        public static string CellPhoneNumberAlreadyVerified {
            get {
                return ResourceManager.GetString("CellPhoneNumberAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن همراه هنوز تایید نشده است!.
        /// </summary>
        public static string CellPhoneNumberIsNotVerified {
            get {
                return ResourceManager.GetString("CellPhoneNumberIsNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با توجه به عملیات انجام شده بر روی رکورد دیگر امکان تایید اول وجود ندارد.
        /// </summary>
        public static string CheckDiscoveryConfirm1 {
            get {
                return ResourceManager.GetString("CheckDiscoveryConfirm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با توجه به عملیات انجام شده بر روی رکورد دیگر امکان تایید دوم وجود ندارد.
        /// </summary>
        public static string CheckDiscoveryConfirm2 {
            get {
                return ResourceManager.GetString("CheckDiscoveryConfirm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابتدا بایستی تایید یا رد اول صورت گیرد.
        /// </summary>
        public static string CheckDiscoveryConfirm2NotConfirm1 {
            get {
                return ResourceManager.GetString("CheckDiscoveryConfirm2NotConfirm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با توجه به عملیات انجام شده بر روی رکورد دیگر امکان رد اول وجود ندارد.
        /// </summary>
        public static string CheckDiscoveryReject1 {
            get {
                return ResourceManager.GetString("CheckDiscoveryReject1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با توجه به عملیات انجام شده بر روی رکورد دیگر امکان رد دوم وجود ندارد.
        /// </summary>
        public static string CheckDiscoveryReject2 {
            get {
                return ResourceManager.GetString("CheckDiscoveryReject2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابتدا بایستی تایید یا رد اول صورت گیرد.
        /// </summary>
        public static string CheckDiscoveryReject2NotConfirm1 {
            get {
                return ResourceManager.GetString("CheckDiscoveryReject2NotConfirm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به دلیل اینکه این رکورد در سایر جداول مورد استفاده قرار گرفته است امکان حذف آن وجود ندارد.
        /// </summary>
        public static string DependentTables {
            get {
                return ResourceManager.GetString("DependentTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشانی پست الکترونیکی قبلا تایید شده است!.
        /// </summary>
        public static string EmailAddressAlreadyVerified {
            get {
                return ResourceManager.GetString("EmailAddressAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشانی پست الکترونیک هنوز تایید نشده است!.
        /// </summary>
        public static string EmailAddressIsNotVerified {
            get {
                return ResourceManager.GetString("EmailAddressIsNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موردی یافت نشد.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات {0} با مشکل مواجه شد..
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت فاکتور با خطا روبرو شده.
        /// </summary>
        public static string ErrorInvoice {
            get {
                return ResourceManager.GetString("ErrorInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای این مورد کشف شده قبلا تقلب صادر شده است.
        /// </summary>
        public static string FraudCheckExists {
            get {
                return ResourceManager.GetString("FraudCheckExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات به درستی وارد نشده است.
        /// </summary>
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصه کاربر یا گذرواژه به درستی وارد نشده است!.
        /// </summary>
        public static string InvalidIdentityOrPassword {
            get {
                return ResourceManager.GetString("InvalidIdentityOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا رمـز عبـور اشتباه است.
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توکن معتبر نمی‌باشد!.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد فعال‌سازی صحیح نمی‌باشد!.
        /// </summary>
        public static string InvalidVerificationKey {
            get {
                return ResourceManager.GetString("InvalidVerificationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اکانت شما به دلیل پنج بار ورود ناموفق به مدت پنج دقیقه قفل شده است.
        /// </summary>
        public static string IsLockedOut {
            get {
                return ResourceManager.GetString("IsLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اکانت شما به دلیل ورود ناموفق تا مدت زمان معینی قفل شده است.
        /// </summary>
        public static string IsLockedUser {
            get {
                return ResourceManager.GetString("IsLockedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمـز عبـور جدید و تکرار رمـز عبـور جدید یکسان نمی‌باشند!.
        /// </summary>
        public static string NewPasswordAndConfirmNewPasswordAreNotEqual {
            get {
                return ResourceManager.GetString("NewPasswordAndConfirmNewPasswordAreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ارسال شده معتبر نمی باشد.
        /// </summary>
        public static string NotVerifyOtpCode {
            get {
                return ResourceManager.GetString("NotVerifyOtpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمـز عبـور قبلی صحیح نمی‌باشد!.
        /// </summary>
        public static string OldPasswordIsNotCorrect {
            get {
                return ResourceManager.GetString("OldPasswordIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ارسال شده منقضی شده، لطفا کد جدیدی دریافت کنید.
        /// </summary>
        public static string OTPExpirationTime {
            get {
                return ResourceManager.GetString("OTPExpirationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما اجازه دسترسی ندارید.
        /// </summary>
        public static string PermissionAccess {
            get {
                return ResourceManager.GetString("PermissionAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری با شماره موبایل وارد شده یافت نشد.
        /// </summary>
        public static string PhoneNotFound {
            get {
                return ResourceManager.GetString("PhoneNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکوردی وجود ندارد.
        /// </summary>
        public static string RecordEmpty {
            get {
                return ResourceManager.GetString("RecordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر دسترسی این عملیات را ندارد.
        /// </summary>
        public static string RegulationActionTypePermissionCheckAccessConfirm {
            get {
                return ResourceManager.GetString("RegulationActionTypePermissionCheckAccessConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال حاضر سرور قادر به پاسخگویی نمی باشد، در زمان دیگری اقدام نمائید.
        /// </summary>
        public static string ServerNotResponse {
            get {
                return ResourceManager.GetString("ServerNotResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای ناشناخته‌ای صورت گرفته است! لطفا با تیم پشتیبانی تماس حاصل فرمایید..
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ورود به سامانه با چنین آی‌پی وجود ندارد!.
        /// </summary>
        public static string YouCanNotLoginWithThisIP {
            get {
                return ResourceManager.GetString("YouCanNotLoginWithThisIP", resourceCulture);
            }
        }
    }
}
