//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages.Validations", typeof(Validations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پذیرنده فروشگاهی.
        /// </summary>
        public static string Acn {
            get {
                return ResourceManager.GetString("Acn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از عملیات {0} مطمئن هستید؟.
        /// </summary>
        public static string ActionConfirm {
            get {
                return ResourceManager.GetString("ActionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد شعبه خریدار.
        /// </summary>
        public static string Bbc {
            get {
                return ResourceManager.GetString("Bbc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه ملی(Bid).
        /// </summary>
        public static string Bid {
            get {
                return ResourceManager.GetString("Bid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پستی خریدار(bpc).
        /// </summary>
        public static string Bpc {
            get {
                return ResourceManager.GetString("Bpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره گذرنامه خریدار.
        /// </summary>
        public static string Bpn {
            get {
                return ResourceManager.GetString("Bpn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حق العمل.
        /// </summary>
        public static string Bros {
            get {
                return ResourceManager.GetString("Bros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه یکتای ثبت قرارداد حق العمل  کاری.
        /// </summary>
        public static string Bsrn {
            get {
                return ResourceManager.GetString("Bsrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای همزمانی رخ داده است.
        /// </summary>
        public static string ConcurrencyFailure {
            get {
                return ResourceManager.GetString("ConcurrencyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجرت ساخت.
        /// </summary>
        public static string Consfee {
            get {
                return ResourceManager.GetString("Consfee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سهم نقدی از پرداخت.
        /// </summary>
        public static string Cop {
            get {
                return ResourceManager.GetString("Cop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه یکتای ثبت  قرارداد فروشنده.
        /// </summary>
        public static string Crn {
            get {
                return ResourceManager.GetString("Crn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع ارز.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای پیشبینی نشده رخ داد.
        /// </summary>
        public static string DefaultError {
            get {
                return ResourceManager.GetString("DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ تخفیف(Dis).
        /// </summary>
        public static string Dis {
            get {
                return ResourceManager.GetString("Dis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [{1}] تکراری است و توسط شخص دیگری انتخاب شده است، لطفا از {0} دیگری استفاده نمایید..
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش {0} قبلا ثبت شده است.
        /// </summary>
        public static string DuplicateRoleName {
            get {
                return ResourceManager.GetString("DuplicateRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار تاریخ می بایست از امروز تا {0} روز گذشته باشد.
        /// </summary>
        public static string EditForSendDateValidation {
            get {
                return ResourceManager.GetString("EditForSendDateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت(Fee).
        /// </summary>
        public static string Fee {
            get {
                return ResourceManager.GetString("Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایلی وجود ندارد.
        /// </summary>
        public static string FileEmpty {
            get {
                return ResourceManager.GetString("FileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ستون {0} تکراری است.
        /// </summary>
        public static string FileExcelColumnDuplicate {
            get {
                return ResourceManager.GetString("FileExcelColumnDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد ستون های تطبیق داده شده برابر نیست.
        /// </summary>
        public static string FileExcelColumnsCount {
            get {
                return ResourceManager.GetString("FileExcelColumnsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ردیف شماره {0} وجود دارد.
        /// </summary>
        public static string FileExcelRow {
            get {
                return ResourceManager.GetString("FileExcelRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ردیف شماره {0} و ستون شماره {1} وجود دارد.
        /// </summary>
        public static string FileExcelRowColumn {
            get {
                return ResourceManager.GetString("FileExcelRowColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل ارسالی معتبر نمی باشد.
        /// </summary>
        public static string FileInvalid {
            get {
                return ResourceManager.GetString("FileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم فایل ارسالی نباید از {0} {1} بیشتر باشد.
        /// </summary>
        public static string FileMaxSize {
            get {
                return ResourceManager.GetString("FileMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خواندن فایل با مشکل مواجه شد.
        /// </summary>
        public static string FileRead {
            get {
                return ResourceManager.GetString("FileRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا یک فایل {0} انتخاب کنید.
        /// </summary>
        public static string FileSelected {
            get {
                return ResourceManager.GetString("FileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل انتخابی قادر به ارسال نمی باشد.
        /// </summary>
        public static string FileZero {
            get {
                return ResourceManager.GetString("FileZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار فیلد {0} باید دقیقا {1} رقم باشد!.
        /// </summary>
        public static string FixLengthNumeric {
            get {
                return ResourceManager.GetString("FixLengthNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار فیلد {0} باید بزرگ‌تر از {1} باشد!.
        /// </summary>
        public static string GreaterThan_FieldValue {
            get {
                return ResourceManager.GetString("GreaterThan_FieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار فیلد {0} باید بزرگ‌تر از مقدار فیلد {1} باشد!.
        /// </summary>
        public static string GreaterThan_TwoFields {
            get {
                return ResourceManager.GetString("GreaterThan_TwoFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار فیلد {0} باید بزرگ‌تر یا مساوی {1} باشد!.
        /// </summary>
        public static string GreaterThanOrEqualTo_FieldValue {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualTo_FieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار فیلد {0} باید بزرگ‌تر یا مساوی مقدار فیلد {1} باشد!.
        /// </summary>
        public static string GreaterThanOrEqualTo_TwoFields {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualTo_TwoFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره سوییچ پرداخت.
        /// </summary>
        public static string Iinn {
            get {
                return ResourceManager.GetString("Iinn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره صورت حساب(Inno).
        /// </summary>
        public static string Inno {
            get {
                return ResourceManager.GetString("Inno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موضوع صورتحساب(Ins).
        /// </summary>
        public static string Ins {
            get {
                return ResourceManager.GetString("Ins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هنگام ثبت.
        /// </summary>
        public static string InsertTime {
            get {
                return ResourceManager.GetString("InsertTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد {0} صحیح نمی‌باشد!.
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} معتبر نیست!.
        /// </summary>
        public static string InvalidProperty {
            get {
                return ResourceManager.GetString("InvalidProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش {0} معتبر نیست.
        /// </summary>
        public static string InvalidRoleName {
            get {
                return ResourceManager.GetString("InvalidRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار {0} معتبر نمی‌باشد!.
        /// </summary>
        public static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره منحصر به فرد مالیاتی  صورتحساب مرجع.
        /// </summary>
        public static string Irtaxid {
            get {
                return ResourceManager.GetString("Irtaxid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا یک {0} انتخاب کنید.
        /// </summary>
        public static string ItemSelected {
            get {
                return ResourceManager.GetString("ItemSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار فیلد {0} باید کوچکتر‌ از {1} باشد!.
        /// </summary>
        public static string LessThan_FieldValue {
            get {
                return ResourceManager.GetString("LessThan_FieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از قبل اکانت خارجی به حساب این کاربر متصل اصت.
        /// </summary>
        public static string LoginAlreadyAssociated {
            get {
                return ResourceManager.GetString("LoginAlreadyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول فیلد {0} می‌تواند حداکثر {1} کاراکتر باشد!.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا مطمئن هستید که می خواهید {0} را باطل کنید؟.
        /// </summary>
        public static string MessageCancel {
            get {
                return ResourceManager.GetString("MessageCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا مطمئن هستید که می خواهید {0} را حذف کنید؟.
        /// </summary>
        public static string MessageDelete {
            get {
                return ResourceManager.GetString("MessageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از خروج مطمئن هستید؟.
        /// </summary>
        public static string MessageLogout {
            get {
                return ResourceManager.GetString("MessageLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول فیلد {0} باید حداقل {1} کاراکتر باشد!.
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد اندازهگیری.
        /// </summary>
        public static string Mu {
            get {
                return ResourceManager.GetString("Mu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار رمز عبور با رمز عبور جدید برابر نمی باشد.
        /// </summary>
        public static string NotEqual {
            get {
                return ResourceManager.GetString("NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} یافت نشد!.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار {0} باید عددی ‌باشد!.
        /// </summary>
        public static string NumberFloatOnly {
            get {
                return ResourceManager.GetString("NumberFloatOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار {0} باید عدد صحیح ‌باشد!.
        /// </summary>
        public static string NumberOnly {
            get {
                return ResourceManager.GetString("NumberOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ سایرمالیات و عوارض.
        /// </summary>
        public static string Odam {
            get {
                return ResourceManager.GetString("Odam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رخ سایرمالیات و عوارض.
        /// </summary>
        public static string Odr {
            get {
                return ResourceManager.GetString("Odr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موضوع سایرمالیات و عوارض.
        /// </summary>
        public static string Odt {
            get {
                return ResourceManager.GetString("Odt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موضوع سایر وجوه قانونی.
        /// </summary>
        public static string Olt {
            get {
                return ResourceManager.GetString("Olt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبلی صحیح نمی‌باشد!.
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باید حداقل دارای یک عدد باشد.
        /// </summary>
        public static string PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("PasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باید حداقل دارای یک کاراکتر انگلیسی کوچک باشد (&apos;a&apos;-&apos;z&apos;).
        /// </summary>
        public static string PasswordRequiresLower {
            get {
                return ResourceManager.GetString("PasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باید حداقل دارای یک کاراکتر ویژه باشد مثل &apos;@#%^&amp;&apos;.
        /// </summary>
        public static string PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باید حداقل دارای {0} کاراکتر منحصر به فرد باشد.
        /// </summary>
        public static string PasswordRequiresUniqueChars {
            get {
                return ResourceManager.GetString("PasswordRequiresUniqueChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باید حداقل دارای یک کاراکتر انگلیسی بزرگ باشد (&apos;A&apos;-&apos;Z&apos;).
        /// </summary>
        public static string PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("PasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نباید کمتر از {0} کاراکتر باشد.
        /// </summary>
        public static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت پرداخت کننده صورتحساب.
        /// </summary>
        public static string Pcn {
            get {
                return ResourceManager.GetString("Pcn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ و زمان پرداخت.
        /// </summary>
        public static string Pdt {
            get {
                return ResourceManager.GetString("Pdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره/شناسه ملی/کد فراگیر اتباع غیر ایرانی پرداخت کننده صورتحساب.
        /// </summary>
        public static string Pid {
            get {
                return ResourceManager.GetString("Pid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا یک مورد را انتخاب کنید . . ..
        /// </summary>
        public static string PleaseSelectOne {
            get {
                return ResourceManager.GetString("PleaseSelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روش پرداخت.
        /// </summary>
        public static string Pmt {
            get {
                return ResourceManager.GetString("Pmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره بیمه نامه.
        /// </summary>
        public static string PolicyNo {
            get {
                return ResourceManager.GetString("PolicyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار فیلد {0} باید بزرگ‌تر یا مساوی {1} و کوچک‌تر یا مساوی {2} باشد..
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار {0} معتبر نمی‌باشد!.
        /// </summary>
        public static string RegularExpression {
            get {
                return ResourceManager.GetString("RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} تکراری است! لطفا از {0} دیگری استفاده نمایید..
        /// </summary>
        public static string Repetitive {
            get {
                return ResourceManager.GetString("Repetitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکمیل {0} الزامی است!.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد شعبه فروشنده.
        /// </summary>
        public static string Sbc {
            get {
                return ResourceManager.GetString("Sbc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد گمرک محل اظهار فروشنده.
        /// </summary>
        public static string Scc {
            get {
                return ResourceManager.GetString("Scc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پروانه  گمرکی.
        /// </summary>
        public static string Scln {
            get {
                return ResourceManager.GetString("Scln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} برای ویرایش انتخاب نشده است.
        /// </summary>
        public static string SelectedId {
            get {
                return ResourceManager.GetString("SelectedId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه کالا(Sstid).
        /// </summary>
        public static string Sstid {
            get {
                return ResourceManager.GetString("Sstid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرح کالا(Sstt).
        /// </summary>
        public static string Sstt {
            get {
                return ResourceManager.GetString("Sstt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره منحصر به فرد مالیاتی.
        /// </summary>
        public static string Taxid {
            get {
                return ResourceManager.GetString("Taxid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره اقتصادی خریدار.
        /// </summary>
        public static string Tinb {
            get {
                return ResourceManager.GetString("Tinb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره اقتصادی فروشنده.
        /// </summary>
        public static string Tins {
            get {
                return ResourceManager.GetString("Tins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پایانه.
        /// </summary>
        public static string Trmn {
            get {
                return ResourceManager.GetString("Trmn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پیگیری/شماره مرجع.
        /// </summary>
        public static string Trn {
            get {
                return ResourceManager.GetString("Trn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر از قبل {0} دارد.
        /// </summary>
        public static string UserAlreadyHasPassword {
            get {
                return ResourceManager.GetString("UserAlreadyHasPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مورد نظر در نقش &apos;{0}&apos; است.
        /// </summary>
        public static string UserAlreadyInRole {
            get {
                return ResourceManager.GetString("UserAlreadyInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قابلیت قفل اکانت کاربر فعال نیست.
        /// </summary>
        public static string UserLockoutNotEnabled {
            get {
                return ResourceManager.GetString("UserLockoutNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مورد نظر در نقش &apos;{0}&apos; نیست.
        /// </summary>
        public static string UserNotInRole {
            get {
                return ResourceManager.GetString("UserNotInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نرخ مالیات بر ارزش افزوده(Vra).
        /// </summary>
        public static string Vra {
            get {
                return ResourceManager.GetString("Vra", resourceCulture);
            }
        }
    }
}
